'use server';
import nodemailer from 'nodemailer';

const EMAIL_USERNAME = process.env.EMAIL_USERNAME!;
const EMAIL_APP_PASSWORD = process.env.EMAIL_APP_PASSWORD!;
const EMAIL_RECEIVER = process.env.EMAIL_RECEIVER!;

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: EMAIL_USERNAME,
        pass: EMAIL_APP_PASSWORD,
    },
});

export async function sendMail({
    email,
    text,
}: {
    email: string;
    text: string;
}) {
    try {
        await transporter.verify();

        const generatedHtml = `
      <div style="font-family: sans-serif; line-height: 1.6;">
        <p>${text.replace(/\n/g, '<br>')}</p>
        <p><strong>FROM:</strong> ${email}</p>
        <hr style="margin-top: 2em;">
        <p style="font-size: 0.9em; color: #888;">
          This email was automatically generated by <strong>HARMONISYS.PH</strong>'s contact footer. Please do not reply directly to this address.
        </p>
      </div>
    `;

        const info = await transporter.sendMail({
            from: `"Harmonisys" <${EMAIL_USERNAME}>`,
            to: EMAIL_RECEIVER,
            subject: 'User Inquiry/Report',
            text: `${text}\n\nFROM: ${email}`,
            html: generatedHtml,
            replyTo: email,
        });

        return info;
    } catch (error) {
        console.error('Email failed to send:', error);
        return null;
    }
}
