export const privateRoutes = [
    '/dashboard',
    '/unahon',
    '/redas',
    '/redas/gis',
    '/irs',
    '/misalud',
    '/hazardhunter',
    '/users',
    '/unahon/form',
    '/misalud/team',
    '/misalud/team/:teamName',
    '/irs/event',
    '/irs/event/:eventName',
    '/redas/appointment',
];
